export const BREADCRUMB_MAP: Record<string, string> = {
  dashboard: "Tableau de bord",
  users: "Utilisateurs",
  categories: "Catégories",
  products: "Produits",
  update: "Éditer",
  edit: "Éditer",
  create: "Créer",
  orders: "Commandes",
  suppliers: "Fournisseurs",
  marketing: "Marketing",
  settings: "Paramètres",
  catalogue: "Catalogue",
  stocks: "Stocks",
  ventes: "Ventes",
  sales: "Ventes",
  invoices: "Factures",
  refunds: "Remboursements",
  stock: "Stocks",
  levels: "État des stocks",
  movements: "Mouvements",
  reports: "Rapports",
  roles: "Rôles & permissions",
  promotions: "Promotions",
  "discount-codes": "Codes de réduction",
  company: "Informations de l'entreprise",
  integrations: "Intégrations",
  security: "Sécurité & accès",
  account: "Mon compte",
  addresses: "Mes adresses",
  wishlist: "Liste de souhaits",
  profile: "Mon profil",
};
