export const ROUTES={
    HOME:"/",
    LOGIN:"/login",
    REGISTER:"/register",
    FORGOT_PASSWORD:"/forgot-password",
    RESET_PASSWORD:"/reset-password",
    CONTACT:"/contact",
    DASHBOARD:"/dashboard",
    DASHBOARD_USERS:"/dashboard/users",
    DASHBOARD_UPDATE_USERS:"/dashboard/users/update",
    DASHBOARD_CREATE_USERS:"/dashboard/users/create",
    DASHBOARD_CATEGORIES:"/dashboard/categories",
    DASHBOARD_CREATE_CATEGORIES:"/dashboard/categories/create",
    DASHBOARD_UPDATE_CATEGORIES:"/dashboard/categories/update",
    DASHBOARD_PRODUCTS:"/dashboard/products",
    DASHBOARD_CREATE_PRODUCTS:"/dashboard/products/create",
    DASHBOARD_UPDATE_PRODUCTS:"/dashboard/products/update",
    DASHBOARD_SALES_ORDERS:"/dashboard/sales/orders",
    DASHBOARD_SALES_INVOICES:"/dashboard/sales/invoices",
    DASHBOARD_SALES_REFUNDS:"/dashboard/sales/refunds",
    DASHBOARD_STOCK_LEVELS:"/dashboard/stock/levels",
    DASHBOARD_STOCK_MOVEMENTS:"/dashboard/stock/movements",
    DASHBOARD_SUPPLIERS:"/dashboard/suppliers",
    DASHBOARD_SUPPLIERS_ORDERS:"/dashboard/suppliers/orders",
    DASHBOARD_REPORTS_SALES:"/dashboard/reports/sales",
    DASHBOARD_REPORTS_STOCK:"/dashboard/reports/stock",
    DASHBOARD_USERS_ROLES:"/dashboard/users/roles",
    DASHBOARD_MARKETING_PROMOTIONS:"/dashboard/marketing/promotions",
    DASHBOARD_MARKETING_DISCOUNTS:"/dashboard/marketing/discount-codes",
    DASHBOARD_SETTINGS_COMPANY:"/dashboard/settings/company",
    DASHBOARD_SETTINGS_INTEGRATIONS:"/dashboard/settings/integrations",
    DASHBOARD_SETTINGS_SECURITY:"/dashboard/settings/security",
    DASHBOARD_ACCOUNT_ORDERS:"/dashboard/account/orders",
    DASHBOARD_ACCOUNT_ADDRESSES:"/dashboard/account/addresses",
    DASHBOARD_ACCOUNT_WISHLIST:"/dashboard/account/wishlist",
    DASHBOARD_ACCOUNT_PROFILE:"/dashboard/account/profile",
    DASHBOARD_PROFILE:"/dashboard/profile",
    DASHBOARD_NOTIFICATIONS:"/dashboard/notifications",
    AUTH_REDIRECT:"/auth/redirect",
    CATEGORIES_LIST:"/categories",
    PRODUCTS_LIST:"/products",
    PRODUCT_DETAIL:(id: number) => `/products/${id}`,
    CART:"/cart",
    CHECKOUT:"/checkout",
    ORDER_CONFIRMATION:(id: number) => `/order-confirmation/${id}`,
    DASHBOARD_ACCOUNT_ORDER_DETAIL:(id: number) => `/dashboard/account/orders/${id}`,
} as const